[opener]
chrome = [
    { run = 'google-chrome-stable "$@"', orphan = true, desc = "Google Chrome" }
]
imagem = [
    { run = 'swayimg "$@"', block = true, desc = "Abrir com Swayimg" }
]

[open]
rules = [
    { mime = "application/pdf", use = "chrome" },
    { mime = "image/*", use = "imagem" }
]
